spring:
  application:
    name: schedule-briefing-ai
  profiles:
    include: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

gcp:
  vertex-ai:
    location: us-central1
    credentials: ${GCP_CREDENTIALS_PATH:}

google:
  application:
    projectId: ${GCP_PROJECT_ID:}

gemini:
  cloud-run:
    url: ${GEMINI_CLOUD_RUN_URL:}